
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chrisdaniar
 */
public class Modul73 extends javax.swing.JFrame {
    String temp="";
    Double ti, bi, hi;

    /**
     * Creates new form Modul73
     */
    public Modul73() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        perempuan = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        coba = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(190, 10, 170, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(70, 60, 60, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tinggi");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(70, 97, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Berat Badan");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(70, 130, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(70, 160, 100, 17);
        jPanel3.add(nama);
        nama.setBounds(210, 50, 210, 30);
        jPanel3.add(tinggi);
        tinggi.setBounds(210, 90, 80, 30);

        jLabel6.setText("kg");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(360, 230, 34, 14);
        jPanel3.add(berat);
        berat.setBounds(210, 130, 80, 30);

        jLabel7.setText("kg");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(290, 100, 34, 14);

        perempuan.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanActionPerformed(evt);
            }
        });
        jPanel3.add(perempuan);
        perempuan.setBounds(200, 160, 110, 23);

        laki.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(laki);
        laki.setText("Laki-laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel3.add(laki);
        laki.setBounds(320, 160, 110, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel3.add(hitung);
        hitung.setBounds(83, 190, 90, 23);

        coba.setText("Coba Lagi");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        jPanel3.add(coba);
        coba.setBounds(190, 190, 120, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel3.add(keluar);
        keluar.setBounds(330, 190, 100, 23);

        jLabel8.setText("Berat badan ideal anda adalah ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 230, 190, 14);

        ideal.setEditable(false);
        jPanel3.add(ideal);
        ideal.setBounds(300, 230, 50, 30);

        jLabel9.setText("kg");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(290, 140, 34, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Hasil Diagnosa Kesehatan");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(170, 270, 240, 22);

        hasil1.setEditable(false);
        jPanel3.add(hasil1);
        hasil1.setBounds(110, 300, 330, 30);

        hasil2.setEditable(false);
        jPanel3.add(hasil2);
        hasil2.setBounds(110, 340, 330, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 560, 440);

        setBounds(0, 0, 581, 476);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
        nama.setText(" ");
        tinggi.setText("");
        berat.setText("");
        buttonGroup1.clearSelection();
        ideal.setText("");
        hasil1.setText("");
        hasil2.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_cobaActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if (nama.getText().equals("")|| tinggi.getText().equals("")
            ||berat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        }else if (perempuan.isSelected()||laki.isSelected()){
            try {
                Proses();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Radio Button harus dipilih");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        laki.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanActionPerformed
        perempuan.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul73.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul73().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coba;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        
        ti = Double.parseDouble(tinggi.getText());
        bi = Double.parseDouble(berat.getText());
        
        if (laki.isSelected()) {
            hi = (ti - 100) * 1;
        } else if (perempuan.isSelected()) {
            hi = (ti - 104) * 1;
        }
        temp = Double.toString(hi.intValue());
        
        if(hi < bi) {
            ideal.setText(temp);
            hasil1.setText( "Maaf " + nama.getText() + " , Sepertinya ada Overweight");
            hasil2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (hi > bi) {
            ideal.setText(temp);
            hasil1.setText( "Maaf " + nama.getText() + " , Sepertinya ada Underweight");
            hasil2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            ideal.setText(temp);
            hasil1.setText( "Maaf " + nama.getText() + " , Berat badan anda sudah ideal");
            hasil2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }
         //To change body of generated methods, choose Tools | Templates.
    }
}
